config/routes.rb
Rails.application.routes.draw do
  resources :storages

  devise_for :users
  get 'users/profile'
  get 'users/settings'

  authenticated :user do
    root :to => "users#profile"
  end

  resources :users do
    member do
      get :storage
    end
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "main#index"
    end
  end
end

app/models/storage.rb
class Storage < ActiveRecord::Base
  belongs_to :user

  def as_json(options={})
    super(only: [:url, :name, :login, :password, :decoderlogin, :decoderpassword, :note, :logo, :favourite, :created_at, :updated_at])
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #has_many :storages
  #attr_accessible :id

  has_many :storages
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
require "rsa"
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #def index
  #  @storage = Storage.new
  #end

  def after_sign_in_path_for(resource)
    users_profile_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController
  def index
    if current_user
      @storages = current_user.storages.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @storages }
      end
    else
      #render json: "Вы должны авторизироваться на сайте"
      render json: { error:true, message: "Вы должны авторизироваться на сайте http://savepass.xxivcreate.xyz/" }
    end

  end

  def show
    @storage = Storage.find(params[:id])
  end

  def new
    #@storage = Storage.new
    @storage = current_user.storages.build
    #super
  end

  def edit
   @storage = Storage.find(params[:id])
  end

  def create
    @storage = current_user.storages.build(storage_params)
    @public_key = current_user.public_key
    @private_key             = File.open("#{Dir.pwd}/private_key/private_key-#{current_user.id}.pem", 'r'){ |file| file.read }
    @storage.login           = Cryptosyst.encrypt( @storage.login, @public_key.to_i )
    @storage.password        = Cryptosyst.encrypt( @storage.password, @public_key.to_i )
    @storage.decoderlogin    = Cryptosyst.decrypt( @storage.login.to_i, @public_key.to_i, @private_key.to_i )
    @storage.decoderpassword = Cryptosyst.decrypt( @storage.password.to_i, @public_key.to_i, @private_key.to_i )
    if @storage.save
      redirect_to root_url
    else
      redirect_to root_url
    end

  end

  def destroy
     @storage  = Storage.find(params[:id])
     @storage.destroy

     render json: { success:true }
  end

  private
  def storage_params
    params.require(:storage).permit(:url, :name, :login, :password, :note)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    if current_user
      @storages = current_user.storages.all
    else
      #render json: "Вы должны авторизироваться на сайте http://savepass.xxivcreate.xyz/"
      render json: { error:true, message: "Вы должны авторизироваться на сайте http://savepass.xxivcreate.xyz/" }
    end

    if current_user && ( current_user.public_key == nil || current_user.exponenta == nil )
      n,exp,d = Cryptosyst.generate_keys( 1024 )
      current_user.update_attributes(:public_key => n, :exponenta =>  exp)
      File.open("#{Dir.pwd}/private_key/private_key-#{current_user.id}.pem", 'w'){ |file| file.write d }
    end
  end

  def index
    if current_user
      @users = User.all
      respond_to do |format|
        format.html
        format.json { render json: @users }
      end
    else
      #render json: "Вы должны авторизироваться на сайте http://savepass.xxivcreate.xyz/"
      render json: { error:true, message: "Вы должны авторизироваться на сайте http://savepass.xxivcreate.xyz/" }
    end
  end


  private
  def storage_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/storages_helper.rb
require 'rubygems'
require 'domainatrix'

module StoragesHelper
  def strip_url(old_url)
    url = Domainatrix.parse(old_url)
    return url.domain
  end

  #new account for 7 day
  def new_for_week(storages)
    @week_day = 0
    @one_day  = 0
    current_time  = Time.now.strftime "%d.%m.%y"
    storages.each do |x|
      storages_time = x.updated_at.strftime "%d.%m.%y"
      new_time = current_time.to_i - storages_time.to_i
      new_time < 1   ?  @one_day  += 1 : @one_day = 0
      new_time <= 7  ?  @week_day += 1 : @week_day = 0
    end
    return @week_day
  end

  def new_for_day
    return @one_day
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SavePass
    meta charset="utf-8"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body#page-top data-spy="scroll" data-target=".navbar-custom"
    = yield
    

app/views/main/_login.html.slim
#mask
.login
  

app/views/main/index.html.slim
.nav.nav-index
  .nav-small
    a.nav-logo href="/"
      img src="/assets/logo/savepass-white.png"
    ul.nav-list
      /li.nav-list-item
        /a.nav-list-link href="#about"  О сервисе
      li.nav-list-item
        a.nav-list-link href="https://chrome.google.com/webstore/detail/savepass/nohkcfoeciegacbdcdohjjjahejjighp?utm_source=chrome-ntp-icon" target="_blink"  Chrome Расширение 
      - if !user_signed_in?
        li.nav-list-item
          a.nav-list-link.js-register= link_to 'Зарегистрироваться', new_user_registration_path
      li.nav-list-item.not_mobile
      - if user_signed_in?
          li.nav-list-item.not_mobile
            a.nav-list-link =link_to 'Выйти', destroy_user_session_path, :method => :delete
      -  else 
          li.nav-list-item.not_mobile
            a.nav-list-link =link_to 'Войти', new_user_session_path
.wrapper
  .intro
    //.intro-right_bg.not_mobile
    .intro-inform
      .intro-header.clear
        .intro-text
          h1 
            /| Упростите свою жизнь.
            | Сделайте жизнь проще
            br 
            | Храните пароли без проблем
          p 
        .intro-btn-sign
          a = link_to new_user_registration_path
            .btn
              p 
                | Начать бесплатно
    .animation_container
      .browser_menu
        .items_menu
          .one.cursor
          .two.cursor
          .three.cursor
  .about#about
    h1 О сервисе
  

app/views/storages/show.html.slim
- Storage.all.each do |x| 
    - if x.user_id == current_user.id
        p=x.url
        p=x.name
        p=x.login
        p=x.password
        p=x.note
        p=x.favourite
= link_to "Назад"

app/views/users/_addform.html.slim
.mask
.form-add
  = simple_form_for Storage.new, :remote => 'true', :html => {:multipart => true, class: "simpleForm"} do |f|
    .form-add-header
      .area.clear
        .row
          .col-xs-3.col-md-3.col-lg-3
            p Добавить сайт
          .col-xs-6.col-md-6.col-lg-6
            .logo
              a.nav-logo href="/"
                img src="/assets/logo/savepass-white.png"
          .col-xs-3.col-md-3.col-lg-3
            .close-size
              //i.fa.fa-arrows-alt.size
              i.fa.fa-close.form-add-close
            
    .form-input
      label URL: 
      = f.input :url, required: false, label: false, input_html: { class: "inputForm fio_form" }, placeholder: false
      label Имя: 
      = f.input :name, required: false, label: false, input_html: { class: "inputForm email_form" }, placeholder: false
      label Имя пользователя:
      = f.input :login, required: false, label: false, input_html: { class: "inputForm phone_form" }, placeholder: false
      label Пароль:
      = f.input :password, required: false, label: false, input_html: { class: "inputForm phone_form" }, placeholder: false
      /label Заметки:
      /= f.input :note, required: false, label: false, input_html: { class: "inputForm phone_form", :cols => 2, :rows => 4 }, placeholder: false
    /= f.text_area :message, required: false, label: false, input_html: { class: "inputForm message_form" }, placeholder: 'Текст сообщения'
    = f.button :submit, 'Отправить', class: 'btn-successable'
    

app/views/users/_contentgrid.html.slim
.site-content-grid
  .area
    .row
      - @storages.each do |x| 
        - if x.user_id == current_user.id
          .col-lg-3.col-md-4.col-sm-6.col-xs-6.pd.cur_item data-item_id=x.id data-item_favourite=x.favourite
            .site-item
              .site-settings
                /label.form-label.check
                  /input type="checkbox" /
                  /span.label-text
                .btn-settings
                  /-if x.favourite == "false"
                  /  i.star.fa.fa-star-o
                  /- else 
                  /  i.star.fa.fa-star
                  /i.edit.fa.fa-edit 
                  i.del.fa.fa-trash
              .site-img
                -if File.exist?("/home/samoht/savepass/app/assets/images/logo-site/#{strip_url(x.url)}.svg")
                  img src="/assets/logo-site/#{strip_url(x.url)}.svg"
                -else 
                  img src=x.logo
              .site-name-and-login
                h4.url =x.name
                h5.mail 
                  a =link_to "#{x.url}", :target => "_blank"
                    =x.url
              a.btn-more.copy-login
                | Скопировать логин  
              a.btn-more.copy-pass
                | Скопировать пароль
              p.hover-login = x.decoderlogin
              p.hover-pass = x.decoderpassword
      .col-lg-3.col-md-4.col-sm-6.col-xs-6.pd.afterrgrid
        .site-item.add-content
          .site-round
            .btn-add-content
              i.add.fa.fa-plus
          .site-name-and-login

app/views/users/_contentlist.html.slim
.site-content-list
  .area
    .row
      ul
        - @storages.each do |x| 
          - if x.user_id == current_user.id
          .all-item.cur_item-list data-item_id=x.id 
            .col-lg-1.col-md-1.col-sm-1.col-xs-1
              .site-img
                -if File.exist?("/home/samoht/savepass/app/assets/images/logo-site/#{strip_url(x.url)}.svg")
                  img src="/assets/logo-site/#{strip_url(x.url)}.svg"
                -else 
                  img src=x.logo
            .col-lg-6.col-md-6.col-sm-6.col-xs-6
              li.list
                .details
                  h3 =x.name
                .btn-settings
                  /i.star.fa.fa-star-o
                  /i.edit.fa.fa-edit
                  i.del.fa.fa-trash
                  a.url href=""
                    =x.url
            .col-lg-5.col-md-5.col-sm-5.col-xs-5
                span 
                  p =x.created_at.strftime("%m/%d/%Y")
                  label.form-label.check
                    input type="checkbox"
                    span.label-text

app/views/users/_editprofile.html.slim
.form-editer
  h1 Настройки профиля
  = simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f|
    = f.error_notification
    .form-inputs
      = f.input :email, label: false, required: true, autofocus: true
      - if devise_mapping.confirmable? && resource.pending_reconfirmation?
        p
          | Currently waiting confirmation for: #{resource.unconfirmed_email}
      = f.input :password, label: false, autocomplete: "off", hint: false, required: false
      = f.input :password_confirmation, label: false, required: false
      = f.input :current_password, label: false, hint: "we need your current password to confirm your changes", required: true
    .form-actions
      = f.button :submit, "Update"
  h3 Cancel my account
  p
    | Unhappy? #{link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete}
  = link_to "Back", :back

app/views/users/_newgrid.html.slim
- @storages.each do |x| 
  - if x.user_id == current_user.id
    .col-lg-3.col-md-4.col-sm-6.col-xs-6.pd.cur_item data-item_id=x.id data-item_favourite=x.favourite
      .site-item
        .site-settings
          label.form-label.check
            input type="checkbox" /
            span.label-text
          .btn-settings 
            i.star.fa.fa-star-o
            i.edit.fa.fa-edit 
            i.del.fa.fa-trash
        .site-img
          img src=x.logo
        .site-name-and-login
          h4.url =x.name
          h5.mail 
            a =link_to "#{x.url}", :target => "_blank"
              =x.url
        a.btn-more
          | Скопировать

app/views/users/_notification.html.slim
.notification
  .success-text
    - if current_user && current_user.storages.last != nil
      h2
        i.fa.fa-check
        | Сайт  
        span= current_user.storages.last.url
        |   добавлен 

app/views/users/_profileset.html.slim
.nav-profile
  .area
    .row
      .col-xs-4.col-sm-6.col-md-6
        .logo
          a.nav-logo href="/"
            img src="/assets/logo/savepass-white.png"
      .col-xs-8.col-sm-6.col-md-6
        .profile-inform.clear
          p.user-email
            = current_user.email
          .img-profile
          i.fa.fa-angle-down
          .menuList 
            ul
              li 
                a.nav-list-link =link_to 'Настройки профиля', users_settings_path
              li 
                a.nav-list-link =link_to 'Выйти', destroy_user_session_path, :method => :delete

app/views/users/_statistics.html.slim
-if @storages.first != nil
  .statistics 
    .area
      .row
        .col-xs-4
          .round 
            h2=@storages.size
          p всего
        .col-xs-4
          .round 
            h2=new_for_week(@storages)
          p новых за неделю
        .col-xs-4
          .round 
            h2=new_for_day
          p новых за день

app/views/users/auth.html.slim
.auth?
  .success-text
    h2
      i.fa.fa-check
      | Сайт
      - if current_user && @storage != nil 
        span= @storages.last.url 
      |   добавлен 

app/views/users/index.html.slim
h1 Users

app/views/users/profile.html.slim
//=render "editprofile"
=render "addform"
=render "notification"
//-if !current_user.auth 
  =render "auth"
.profile
  =render "profileset"
  .bar-profile  
    .area
      .row
        .col-lg-10.col-xs-8.col-sm-8.col-md-10
          .wrapper
            .icon-search-container data="search-trigger" 
              span.fa.fa-search
              input.search-input data="search-input" placeholder="Поиск" type="text" /
              span.fa.fa-times-circle data="search-clear" 

        .col-lg-2.col-xs-4.col-sm-4.col-md-2
          .grid-or-list
            i.fa.fa-th.grid
            i.fa.fa-list.list
  .btn-add
    i.add.fa.fa-plus
  =render "statistics"
  =render "contentgrid"
  =render "contentlist"

app/views/users/settings.html.slim
=render "profileset"
.settings    
  .title-email
    h1 Настройки
  .area.edit-profile
    .row
      .col-xs-6
        .edit-fio
          h2.fio =current_user.email
          .btn 
            | Редактировать
      .col-xs-6
        .edit-photo
          img src= current_user.storages.last.logo
  span.heading-title Настройки email
  .email-settings
    .area
      .row
        .col-xs-6
          h2.list-itemTitle Ваш email
          h4.light = current_user.email
        .col-xs-6
          p Редактировать
    .area
      .row
        .col-xs-6
          h2.list-itemTitle Подписка на рассылку
          p.other-text Контроль электронных писем, которые мы посылаем вам.
        .col-xs-6
          p Редактировать
  .title-security
    span.heading-title Безопасность
  .security-settings
    .area
      .row
        .col-xs-6
          h2.list-itemTitle Изменить пароль

        .col-xs-6
          p Изменить
    .area
      .row
        .col-xs-6
          h2.list-itemTitle Выйти из всех остальных сеансов
        .col-xs-6
          p Выйти
    .area
      .row
        .col-xs-6
          h2.list-itemTitle Деактивировать аккаунт
          p.other-text
            | Отключение учетной записи будут удалены из среды в течение нескольких минут. Вы можете снова войти в любое время, чтобы активировать свою учетную запись и восстановить его содержимое.
        .col-xs-6
          p Деактивировать
    .area
      .row
        .col-xs-6
          h2.list-itemTitle Удалить аккаунт
          p.other-text 
            | Полностью удалить учетную запись и все содержимое.
        .col-xs-6
          p Удалить
    .area
      .row
        .col-xs-6
          h2.list-itemTitle История активности
          p.other-text =current_user.last_sign_in_at.strftime("%d/%m/%y в %I:%M%p") 
          p.other-text =current_user.last_sign_in_ip
        .col-xs-6
          p Показать историю активности
  